### ISSUE TITLE
Navbar style off in iOS emulator

### ISSUE THREAD

**Issue by xbili** [LetterboxDev/frontend#13]
![simulator screen shot 10 oct 2015 11 05 02 am](https://cloud.githubusercontent.com/assets/4846457/10408932/c6d57176-6f3e-11e5-9466-22d88b3f8518.png)

Very odd, probably an issue with our styling. Will read up about this.

**Comment by lozy219** [comment]
the problem is, on ios, there is a 20px _status bar_ on top, it will be counted in the `$nav-bar-height`, but every other elements will be positioned starting from the bottom of the status bar. if you add an extra 20px to our `$nav-bar-height`, the navbar style should be corrected
![image](https://cloud.githubusercontent.com/assets/6064797/10411428/cc5c4db4-6f97-11e5-8230-f72e500f17ce.png)

**Comment by sebastianquek** [comment]
:+1: Now the "LETTERBOX" word needs to be vertically aligned with the button on the left.

**Comment by lozy219** [comment]
@sebastianquek sorry it's 20 instead of 15...(and I put 25 in the previous screenshot) 
here is the 20px one:
![image](https://cloud.githubusercontent.com/assets/6064797/10411446/daff3e16-6f98-11e5-965b-be29ed98fbbb.png)
